# Setup anyenv (see https://github.com/riywo/anyenv)
export PATH="$HOME/.anyenv/bin:$PATH"
eval "$(anyenv init -)"

# Go settings.
export GOBIN=$HOME/.gobin
export PATH=$PATH:$GOBIN

# Rust settings.
source $HOME/.cargo/env
export PATH=$PATH:$HOME/.cargo/bin

# Activate virtualenv
source ~/.venv/bin/activate

# Up history size.
HISTSIZE=100000

# SSH key setting.
ssh-add -K ~/.ssh/id_rsa 2>/dev/null

# Setup aliases
alias nv=nvim
alias g=git
