# Zsh options.
setopt interactivecomments

# Setup anyenv (see https://github.com/riywo/anyenv)
# export PATH="$HOME/.anyenv/bin:$PATH"
# eval "$(anyenv init -)"

# Go settings.
# export GOBIN=$HOME/.gobin
# export PATH="$GOBIN:$PATH"

# Rust settings.
# source $HOME/.cargo/env
# export PATH="$HOME/.cargo/bin:$PATH"

# Activate virtualenv
source ~/.venv/bin/activate

# Up history size.
HISTSIZE=100000

# SSH key setting.
ssh-add --apple-use-keychain

# Setup aliases
alias nv=nvim
alias g=git
